spring.application.name=khallikarao

spring.datasource.url = jdbc:postgresql://localhost:5432/khallikarao
spring.datasource.username = postgres
spring.datasource.password = postgres123
spring.datasource.driver-class-name = org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.hikari.auto-commit=false

jwt.secret=${d7lOipyWgjmKzJykkKQV5LVvmhyg98SWMoisMM7egPA=}
jwt.expiration-seconds=3600

spring.mail.host=${SMTP_HOST}
spring.mail.port=587
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

app.mail.from=${SMTP_USERNAME}